### ISSUE TITLE
PHP Deprecated:  mb_convert_encoding(): Handling HTML entities via mbstring is deprecated

### ISSUE THREAD

**Issue by daniporr** [aledeg/xExtension-RedditImage#10] opened 2023-02-13 13:32 UTC
PHP Deprecated:
mb_convert_encoding(): Handling HTML entities via mbstring is deprecated;
use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead
in `Content.php`
on line 20

**Comment by aledeg** [comment] 2023-02-22 05:24
Thank you for the notice. It's fixed in the `main` branch. It will be available in the next release.

**Comment by daniporr** [comment] 2023-02-25 17:45
Thank you very much!

**Comment by daniporr** [comment] 2023-02-26 23:58
@aledeg do you already know when the new version will be released?

**Comment by aledeg** [comment] 2023-02-27 16:09
Not yet. I have a few things to do before. The problem is I do not have much time to put on it.

**Comment by aledeg** [comment] 2023-03-02 02:23
My fix breaks other things :/

**Comment by aledeg** [comment] 2023-03-02 04:07
I think it's working now.

**Closed by aledeg** 2023-03-02 04:07 UTC

**Comment by aledeg** [comment] 2023-03-04 13:28
> @aledeg do you already know when the new version will be released?

It might be sooner than expected. If found some time to work on that. But there something fishy since I cannot get reddit galleries while refreshing a feed. But when it's a new feed it works.
It does the same thing with previous versions too.

But only on my dev instance. I do not understand what's going on.

**Comment by daniporr** [comment] 2023-04-10 14:05
Thank you for your answer.
